import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faHouse,
  faTableList,
  faBullseye,
  faChartLine,
  faChartBar,
  faBoxArchive,
  faGear,
  faWallet,
  faBuildingColumns,
  faMoneyBill,
  faArrowTrendUp,
  faChevronRight,
  faPlus,
  faCalendarDays,
  faBolt,
  faTrash,
  faPen,
  faCheck,
  faXmark,
  faMoon,
  faSun,
  faPiggyBank,
  faCreditCard,
  faFileInvoice,
  faArrowRight,
  faEye,
  faTriangleExclamation,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faHouse,
  faTableList,
  faBullseye,
  faChartLine,
  faChartBar,
  faBoxArchive,
  faGear,
  faWallet,
  faBuildingColumns,
  faMoneyBill,
  faArrowTrendUp,
  faChevronRight,
  faPlus,
  faCalendarDays,
  faBolt,
  faTrash,
  faPen,
  faCheck,
  faXmark,
  faMoon,
  faSun,
  faPiggyBank,
  faCreditCard,
  faFileInvoice,
  faArrowRight,
  faEye,
  faTriangleExclamation,
)

export { FontAwesomeIcon }
